import {
  MAIL_INTERVIEW_CANCELLED_EVENT_NAME,
  MAIL_INTERVIEW_CREATED_EVENT_NAME,
  MAIL_INTERVIEW_UPDATED_EVENT_NAME,
  MAIL_OFFER_SENT_EVENT_NAME
} from '@careerhub/contracts';

export const RECRUITMENT_MAIL_QUEUE = 'communication.recruitment-mail';

export const RECRUITMENT_MAIL_ROUTING_KEYS = [
  MAIL_INTERVIEW_CREATED_EVENT_NAME,
  MAIL_INTERVIEW_UPDATED_EVENT_NAME,
  MAIL_INTERVIEW_CANCELLED_EVENT_NAME,
  MAIL_OFFER_SENT_EVENT_NAME
] as const;

export const RECRUITMENT_MAIL_CONSUMER = 'communication-recruitment-mail';
