INSERT INTO "benefit_catalogs" (
    "id",
    "code",
    "label",
    "description",
    "has_monetary_value_default",
    "requires_amount",
    "requires_frequency",
    "requires_annual_leave_days",
    "is_active",
    "is_selectable",
    "sort_order",
    "updated_at"
)
VALUES
    (
        'bc-private_healthcare',
        'private_healthcare',
        'Private Healthcare',
        'Additional health insurance beyond statutory coverage',
        false,
        false,
        false,
        false,
        true,
        true,
        1,
        CURRENT_TIMESTAMP
    ),
    (
        'bc-remote_allowance',
        'remote_allowance',
        'Remote Work Allowance',
        'Stipend for home office equipment and setup',
        true,
        true,
        true,
        false,
        true,
        true,
        2,
        CURRENT_TIMESTAMP
    ),
    (
        'bc-training_budget',
        'training_budget',
        'Training Budget',
        'Budget for courses, books, and learning resources',
        false,
        false,
        false,
        false,
        true,
        true,
        3,
        CURRENT_TIMESTAMP
    ),
    (
        'bc-thirteenth_month',
        'thirteenth_month',
        '13th Month Salary',
        'Bonus equivalent to one month''s salary',
        false,
        false,
        false,
        false,
        true,
        true,
        4,
        CURRENT_TIMESTAMP
    ),
    (
        'bc-annual_leave',
        'annual_leave',
        'Annual Leave',
        'Paid time off days in addition to public holidays',
        false,
        false,
        false,
        true,
        true,
        true,
        5,
        CURRENT_TIMESTAMP
    ),
    (
        'bc-health_insurance',
        'health_insurance',
        'Health Insurance',
        'Mandatory social insurance contributions in Vietnam',
        false,
        false,
        false,
        false,
        true,
        false,
        6,
        CURRENT_TIMESTAMP
    )
ON CONFLICT ("code") DO UPDATE SET
    "label" = EXCLUDED."label",
    "description" = EXCLUDED."description",
    "has_monetary_value_default" = EXCLUDED."has_monetary_value_default",
    "requires_amount" = EXCLUDED."requires_amount",
    "requires_frequency" = EXCLUDED."requires_frequency",
    "requires_annual_leave_days" = EXCLUDED."requires_annual_leave_days",
    "is_active" = EXCLUDED."is_active",
    "is_selectable" = EXCLUDED."is_selectable",
    "sort_order" = EXCLUDED."sort_order",
    "updated_at" = EXCLUDED."updated_at";
