import { ConfigModule, type ConfigModuleOptions, type ConfigService } from '@nestjs/config';
import { type EnvironmentVariables } from './env.schema';
export type RuntimeNodeEnv = EnvironmentVariables['NODE_ENV'];
export type RuntimeLogLevel = EnvironmentVariables['LOG_LEVEL'];
export type RuntimeConfig = {
    brokerDeadLetterEnabled: boolean;
    brokerDeadLetterPrefix: string;
    brokerDurable: boolean;
    brokerExchangePrefix: string;
    brokerPrefetchCount: number;
    brokerQueuePrefix: string;
    brokerUrl?: string;
    databaseUrl?: string;
    healthEnabled: boolean;
    healthLivenessPath: string;
    healthPath: string;
    healthReadinessPath: string;
    httpLogEnabled: boolean;
    logFilePath?: string;
    logLevel: RuntimeLogLevel;
    logPretty: boolean;
    metricsEnabled: boolean;
    metricsPath: string;
    nodeEnv: RuntimeNodeEnv;
    otelEnabled: boolean;
    otelExporterOtlpEndpoint?: string;
    otelExporterOtlpProtocol?: string;
    otelServiceName?: string;
    otelTracesSampler?: string;
    otelTracesSamplerArg?: string;
    port: number;
    redisUrl?: string;
    serviceName: string;
};
type RuntimeConfigModuleOptions = Omit<ConfigModuleOptions, 'validate'> & {
    validate?: ConfigModuleOptions['validate'];
};
export declare function createRuntimeConfigModule(options?: RuntimeConfigModuleOptions): ReturnType<typeof ConfigModule.forRoot>;
export declare function loadRuntimeConfig(env?: NodeJS.ProcessEnv): RuntimeConfig;
export declare function getRuntimeConfig(configService: Pick<ConfigService<EnvironmentVariables, true>, 'get' | 'getOrThrow'>): RuntimeConfig;
export declare const createRuntimeConfig: typeof loadRuntimeConfig;
export {};
