apiVersion: 1

contactPoints:
  - orgId: 1
    name: CareerHub Email
    receivers:
      - uid: careerhub-email
        type: email
        settings:
          addresses: '${GF_ALERT_EMAIL_TO}'
          singleEmail: false
