import type { IntegrationConsumerDurationMetricRecord, HttpErrorMetricRecord, HttpMetricRecord, IntegrationConsumerMetricRecord, MetricsRegistry, OutboxBacklogMetricRecord, OutboxCleanupMetricRecord, OutboxPublishMetricRecord, RegisterCompensationMetricRecord, RmqMetricRecord, RpcMetricRecord } from './metrics.types';
export declare class InMemoryMetricsRegistry implements MetricsRegistry {
    private readonly httpErrorsTotal;
    private readonly httpRequestsDuration;
    private readonly httpRequestsTotal;
    private readonly rpcRequestsTotal;
    private readonly rpcErrorsTotal;
    private readonly rpcRequestsDuration;
    private readonly rmqMessagesTotal;
    private readonly rmqErrorsTotal;
    private readonly rmqMessagesDuration;
    private readonly outboxPublishTotal;
    private readonly outboxCleanupDeletedTotal;
    private readonly outboxBacklogGauge;
    private readonly outboxOldestPendingAgeGauge;
    private readonly integrationConsumerTotal;
    private readonly integrationConsumerDuration;
    private readonly registerCompensationTotal;
    recordHttpRequest(record: HttpMetricRecord): void;
    recordHttpError(record: HttpErrorMetricRecord): void;
    recordIntegrationConsumer(record: IntegrationConsumerMetricRecord): void;
    recordIntegrationConsumerDuration(record: IntegrationConsumerDurationMetricRecord): void;
    recordRegisterCompensation(record: RegisterCompensationMetricRecord): void;
    recordOutboxBacklog(record: OutboxBacklogMetricRecord): void;
    recordOutboxCleanup(record: OutboxCleanupMetricRecord): void;
    recordOutboxPublish(record: OutboxPublishMetricRecord): void;
    recordRpcRequest(record: RpcMetricRecord): void;
    recordRpcError(record: RpcMetricRecord): void;
    recordRmqRequest(record: RmqMetricRecord): void;
    recordRmqError(record: RmqMetricRecord): void;
    renderPrometheus(): string;
    private createRmqLabels;
    private incrementCounter;
    private observeSummary;
    private renderCounterMetric;
    private renderSummaryMetric;
    private renderGaugeMetric;
    private setGauge;
    private parseLabelKey;
}
